# Generate Dataset Greek More Data

## Combination of Greek Words

In [1]:
import pandas as pd
import csv
greek_corpus = pd.read_csv('Greek_wordlist.txt', sep="\t", header=None, quoting=csv.QUOTE_NONE)

In [2]:
dictionary = pd.read_csv('greek_eng_dict_v2.txt', sep="\t", header=None, quoting=csv.QUOTE_NONE)
symbol_dict = dictionary.iloc[135:]
symbol_dict = symbol_dict.reset_index(drop=True)

In [3]:
greek_corpus

                  0
0               και
1                να
2                το
3               του
4               την
...             ...
143955    ΚΑΚΟΗΘΟΥΣ
143956    ΗΛΙΑΧΤΙΔΑ
143957   ΠΡΕΣΒΕΥΕΙΣ
143958     ΕΦΑΜΙΛΛΗ
143959  ΜΕΓΕΘΥΝΤΙΚΟ

[143960 rows x 1 columns]

In [4]:
dictionary

     0
0    Α
1    Β
2    Γ
3    Δ
4    Ε
..  ..
161  +
162  ,
163  -
164  .
165  /

[166 rows x 1 columns]

In [5]:
symbol_dict

,0
0,;
1,<
2,=
3,>
4,?
5,@
6,[
7,\
8,]
9,^
10,_
11,`
12,{
13,|
14,}
15,~
16,!
17,""""
18,#
19,$
20,%
21,&
22,'
23,(
24,)
25,*
26,+
27,","
28,-
29,.
30,/

## Data Cleansing for Greek Dataset

In [6]:
dict_list = list(dictionary[0])

remove_list = []

for i, txt in enumerate(greek_corpus[0]):
    try:
        for j in txt:
            if j in dict_list:
                pass
            else:
                remove_list.append(i)
                continue
    except:
        remove_list.append(i)

In [7]:
greek_corpus_avalible = greek_corpus.drop(index=remove_list)
greek_corpus_avalible = greek_corpus_avalible.reset_index(drop=True)
greek_corpus_avalible

                  0
0               και
1                να
2                το
3               του
4               την
...             ...
143828    ΚΑΚΟΗΘΟΥΣ
143829    ΗΛΙΑΧΤΙΔΑ
143830   ΠΡΕΣΒΕΥΕΙΣ
143831     ΕΦΑΜΙΛΛΗ
143832  ΜΕΓΕΘΥΝΤΙΚΟ

[143833 rows x 1 columns]

In [8]:
with open('Greek_corpus_v2.txt', 'w') as z:

    for i in greek_corpus_avalible[0]:
        z.write(i)
        z.write('\n')

## Data Cleansing for English Dataset

In [9]:
eng_corpus = pd.read_csv('eng.wordlist', sep="\t", header=None, quoting=csv.QUOTE_NONE)

In [10]:
eng_corpus

                  0
0               the
1                of
2               and
3                to
4                 a
...             ...
439145     Cycling:
439146  variation).
439147     people.'
439148       Minhtu
439149      Gaming?

[439150 rows x 1 columns]

In [11]:
dict_list = list(dictionary[0])

remove_list = []

for i, txt in enumerate(eng_corpus[0]):
    try:
        for j in txt:
            if j in dict_list:
                pass
            else:
                remove_list.append(i)
                continue
    except:
        remove_list.append(i)

In [12]:
eng_corpus_avalible = eng_corpus.drop(index=remove_list)
eng_corpus_avalible = eng_corpus_avalible.reset_index(drop=True)
eng_corpus_avalible

                  0
0               the
1                of
2               and
3                to
4                 a
...             ...
399651     Cycling:
399652  variation).
399653     people.'
399654       Minhtu
399655      Gaming?

[399656 rows x 1 columns]

In [13]:
with open('English_corpus.txt', 'w') as z:

    for i in eng_corpus_avalible[0]:
        z.write(i)
        z.write('\n')

## Generate Combined Text

In [16]:
import random

n_sample = 100

for i in range(n_sample):

    # Whether the text is combined by english and greek

    greek_eng = random.randint(0,1)

    if greek_eng:

        # Set english first or greek first

        eng_first = random.randint(0,1)

        if eng_first:

            # Pick Words in Corpus

            f = random.randint(0,len(eng_corpus_avalible)-1)
            s = random.randint(0,len(greek_corpus_avalible)-1)

            # Pick Symbols in List

            fs = random.randint(0,len(symbol_dict)-1)
            ss = random.randint(0,len(symbol_dict)-1)

            # Add Space at Random

            space = random.randint(0,1)

            # Merge
            if space == 1:
                string = eng_corpus_avalible.iloc[f][0] + symbol_dict.iloc[fs][0] + ' ' + greek_corpus_avalible.iloc[s][0] + symbol_dict.iloc[ss][0]
            else:
                string = eng_corpus_avalible.iloc[f][0] + symbol_dict.iloc[fs][0] + greek_corpus_avalible.iloc[s][0] + symbol_dict.iloc[ss][0]

        else:

            # Pick Words in Corpus

            f = random.randint(0,len(greek_corpus)-1)
            s = random.randint(0,len(eng_corpus_avalible)-1)

            # Pick Symbols in List

            fs = random.randint(0,len(symbol_dict)-1)
            ss = random.randint(0,len(symbol_dict)-1)

            # Add Space at Random

            space = random.randint(0,1)

            # Merge
            if space == 1:
                string = greek_corpus.iloc[f][0] + symbol_dict.iloc[fs][0] + ' ' + eng_corpus_avalible.iloc[s][0] + symbol_dict.iloc[ss][0]
            else:
                string = greek_corpus.iloc[f][0] + symbol_dict.iloc[fs][0] + eng_corpus_avalible.iloc[s][0] + symbol_dict.iloc[ss][0]

    else:

        # Pick Words in Corpus

        f = random.randint(0,len(greek_corpus)-1)
        s = random.randint(0,len(greek_corpus)-1)

        # Pick Symbols in List

        fs = random.randint(0,len(symbol_dict)-1)
        ss = random.randint(0,len(symbol_dict)-1)

        # Add Space at Random

        space = random.randint(0,1)

        # Merge
        if space == 1:
            string = greek_corpus.iloc[f][0] + symbol_dict.iloc[fs][0] + ' ' + greek_corpus.iloc[s][0] + symbol_dict.iloc[ss][0]
        else:
            string = greek_corpus.iloc[f][0] + symbol_dict.iloc[fs][0] + greek_corpus.iloc[s][0] + symbol_dict.iloc[ss][0]

    if len(string) >= 25:
        string = string[0:25]

    print(string)

αντικατοπτρίζονται,ΚΙΝΗΘΕ
ΜΙΚΕΛΑΝΤΖΕΛΟ|αμβρόσιος{
ΜΕΤΑΤΑΞΕΙΣ`πεινάω\
ΔΙΕΘΝΗ;ιερής}
Gurbani` άκουσον?
ΜΕΛΑΝΙ(queen's?
προδιαγεγραμμένο$ φαίη}
επιπεδου. εκλεκτή^
quickly:~ ΙΔΙΟΤΗΤΑ"
ΑΠΙΘΑΝΕΣ+περιόδευσε/
παρεκτροπή- ΒΓΑΛΕ\
προσθέσουμε+ΠΑΤΟΥΣΑ}
χαρτι@μετάνοια<
ΑΠΡΟΚΑΛΥΠΤΗ`ΠΕΡΙΣΤΡΕΦΟΜΕΝ
ΠΡΩΤΕΣ. ΔΙΠΛΑΣΙΑΣΤΗΚΕ[
Ω~ WIZARDS<
αποκλείουν; αγωγιμότητα>
παρατήρησε{unfamiliar,
coordinating,@παρεμποδίζο
Turnhere, κυπρο=
fact.( ΧΑΡΑΚΤΗΡΙΖΕΙ_
ΚΑΘΕΔΡΙΚΟΥ[NECK~
ΖΥΡΙΧΗ) ειδησεων^
ιχθύος;θυμηθείς;
τελωνειακή* ΠΑΛΙΟΤΕΡΑ$
Amalie" φλερτάρουν}
prac-$στέλλας-
φάτε'W...&
παράλληλα" ΦΑΝΟΥΛΛΑ/
ΚΑΤΑΧΝΙΑ<glamor|
reign\ ΔΙΑΠΙΣΤΕΥΤΗΡΙΑ<
αποδεδειγμένο)ΠΙΕΡ*
ΕΠΕΞΕΡΓΑΖΕΤΑΙ/ Mans(
χρησίμευε- Haidar,
εισηγμένης)σκοτώνονται,
ΘΡΗΝΟΣ[ ντεμέκ&
λιγους/ διορθώνω?
εγκεφαλικά&ΔΑΣΑΡΧΕΙΟ'
ΚΛΙΜΑΤΙΣΤΙΚΑ^ΕΠΕΜΕΝΑΝ;
γεννιέσαι%Streator~
Falta@ γειτνιάζουν^
οποίου}ΟΝΟΜΑ%
piece.]αποδεχτείς>
έκαστον? Papermaking}
άρια!εκπ<
ΑΝΑΛΑΒΩ"anniversaries,>
αναφέροντας` ΟΜΟΡΦΗΣ%
επαναλάβουν[ Analogously,
ΕΜΦΑΝΙΣΤΩ^ ΒΑΘΙΕΣ_
γκάνγκστερ- handicap.\
συλλέγουν` ΚΑΤΑΒΑΛΛΟΥΜΕ}
Anjou;ΚΑΙΣΑΡΑΣ^
ΙΣΡΑΗΛΙΝΟΣ-ΚΑΤΑΤΙΘΕΤΑΙ'
ΕΛΟΣ[ Harborne?
ΑΔΕΛΦΟΥ. πλαίσιο'
Wheels:!ΓΕΙΤΟΝΙΑ/
ΒΛΑΒΗΣ% Scarecrow%
καρφίτσες-ΕΜΠΙΠΤΟΥΝ$
έκλαιγα@ ΤΣΕΧΙΚΗ=
απεργούς+ΕΠΑΙΞΕ[
ΦΘΙΝΟΠΩΡΙΝΟ^ ανυπέρβλητη#
αφαιρέσεις=Celtics.+
ppnow? ποτέ=
διαχειριστεί&ΕΓΚΑΤΑΣΤΗΣΩ#
ΑΔΕΙΟΙ, ξάδελφο\
ΠΡΑΚΤΙΚΗΣ!spring,{
ΚΑΡΕΖΗ>μητρότητα|
Bryanston&ΚΛΩΝΟΠΟΙΗΣΗΣ`
crux?ΚΑΛΩΣΟΡΙΣΜΑ_
ΤΟΥΡΚΙΚΟ' τετραετίας^
ΜΕΤΑΒΑΤΙΚΗΣ? Tracking,>
Gandhi,-τρομερό;
"climate&μελετημένη_
ΙΔΕΟΛΟΓΙΚΟ\MacMost}
κίρικο/ προδώσουν<
ΑΠΟΦΑΣΙΣΕ~ εκπαιδευτική|
ΤΡΙΑΝΤΑΠΕΝΤΕ+ υγρή;
ΣΥΝΩΜΟΣΙΟΛΟΓΙΑ$ ΔΗΜΟΣΙΟΠΟ
ΙΔΙΟΚΤΗΣΙΕΣ<Beller,
ΑΝΘΡΑΚΑΣ! ΒΕΛΟΥΔΟ-
ΑΝΔΡΙΚΗ+ ΨΥΧΡΩΝ~
ΣΤΑΖΕΙ_υπηρεσιακός`
αναρωτιόταν}he:<
ΑΤΥΧΟΥΣ-quietly.#
τυποποιημένων-ΘΟΔΩΡΟ$
κασσίμης=ΟΠΑΔΟΥΣ-
ΕΠΑΛΗΘΕΥΣΗΣ(ΓΗΣ[
ΔΙΑΓΡΑΦΕΤΑΙ[ εφηβεία=
ΚΑΤΕΥΘΥΝΟΝΤΑΝ= IIC)
ΑΧΑΝΗ- ΟΡΓΑΝΑ"
χοάνες~ ΠΑΡΑΔΕΧΟΝΤΑΝ%
ΦΩΤΕΙΝΟΣ* ΒΟΥΒΑ+
ΠΑΡΑΔΕΙΣΟΥ{ δούλευα`
ΔΙΑΒΗΜΑΤΑ_ορμητήριο!
άκρατος{ ΣΤΟΙΧΕΙΩΔΗΣ{
ΠΑΠΑΓΙΑΝΝΑΚΗΣ.typ[
Astigmatism*δευτέραν+
ΤΑΛΑΝΤΩΣΗΣ&ΡΑΔΙΟ+
ΓΑΛΛΙΚΩΝ) ΜΕΛΑΝΙΑ!
αλληλέγγυα@ Mono,+

In [17]:
import random

n_sample = 100000

with open('corpus_v2.txt', 'w') as z:

    for i in range(n_sample):
        
        # Whether the text is combined by english and greek
        
        greek_eng = random.randint(0,1)
        
        if greek_eng:
            
            # Set english first or greek first
            
            eng_first = random.randint(0,1)
            
            if eng_first:

                # Pick Words in Corpus

                f = random.randint(0,len(eng_corpus_avalible)-1)
                s = random.randint(0,len(greek_corpus_avalible)-1)

                # Pick Symbols in List

                fs = random.randint(0,len(symbol_dict)-1)
                ss = random.randint(0,len(symbol_dict)-1)

                # Add Space at Random

                space = random.randint(0,1)

                # Merge
                if space == 1:
                    string = eng_corpus_avalible.iloc[f][0] + symbol_dict.iloc[fs][0] + ' ' + greek_corpus_avalible.iloc[s][0] + symbol_dict.iloc[ss][0]
                else:
                    string = eng_corpus_avalible.iloc[f][0] + symbol_dict.iloc[fs][0] + greek_corpus_avalible.iloc[s][0] + symbol_dict.iloc[ss][0]
            
            else:
                
                # Pick Words in Corpus

                f = random.randint(0,len(greek_corpus_avalible)-1)
                s = random.randint(0,len(eng_corpus_avalible)-1)

                # Pick Symbols in List

                fs = random.randint(0,len(symbol_dict)-1)
                ss = random.randint(0,len(symbol_dict)-1)

                # Add Space at Random

                space = random.randint(0,1)

                # Merge
                if space == 1:
                    string = greek_corpus_avalible.iloc[f][0] + symbol_dict.iloc[fs][0] + ' ' + eng_corpus_avalible.iloc[s][0] + symbol_dict.iloc[ss][0]
                else:
                    string = greek_corpus_avalible.iloc[f][0] + symbol_dict.iloc[fs][0] + eng_corpus_avalible.iloc[s][0] + symbol_dict.iloc[ss][0]
            
        else:
            
            # Pick Words in Corpus

            f = random.randint(0,len(greek_corpus_avalible)-1)
            s = random.randint(0,len(greek_corpus_avalible)-1)

            # Pick Symbols in List

            fs = random.randint(0,len(symbol_dict)-1)
            ss = random.randint(0,len(symbol_dict)-1)

            # Add Space at Random

            space = random.randint(0,1)

            # Merge
            if space == 1:
                string = greek_corpus_avalible.iloc[f][0] + symbol_dict.iloc[fs][0] + ' ' + greek_corpus_avalible.iloc[s][0] + symbol_dict.iloc[ss][0]
            else:
                string = greek_corpus_avalible.iloc[f][0] + symbol_dict.iloc[fs][0] + greek_corpus_avalible.iloc[s][0] + symbol_dict.iloc[ss][0]

        if len(string) >= 25:
            string = string[0:25]

        # print(string)

        z.write(string)
        z.write('\n')